# Generated by Django 5.1 on 2024-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tva",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
