# Generated by Django 5.1 on 2024-08-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="amount",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
