# Generated by Django 5.1 on 2024-08-29 21:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_remove_invoice_amount_alter_invoice_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="reference",
        ),
    ]
