# Generated by Django 5.1 on 2024-08-29 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_remove_invoice_reference"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="invoicedetail",
            unique_together=set(),
        ),
    ]
