# Generated by Django 5.1 on 2024-08-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_alter_invoicedetail_unique_together"),
        ("products", "0002_alter_product_tva"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="invoicedetail",
            unique_together={("invoice", "product")},
        ),
    ]
