# Generated by Django 5.1 on 2024-08-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0005_invoice_amount_invoice_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
