# Generated by Django 5.1 on 2024-08-28 21:39

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="country",
            field=django_countries.fields.CountryField(
                default="TG", max_length=2, verbose_name="country"
            ),
        ),
    ]
