# Generated by Django 4.2.15 on 2024-09-02 09:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number2",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=30,
                null=True,
                region=None,
                verbose_name=" second phone number",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+22891271298",
                max_length=30,
                region=None,
                verbose_name=" first phone number",
            ),
        ),
    ]
